#!/usr/bin/env bash
# Build AltTab from an already-unlocked checkout.
# Usage: build.sh <checkout-dir> <version> [output-dir]
#
# Builds ad-hoc, then re-signs with $SIGN_IDENTITY when set (plus $SIGN_KEYCHAIN if the identity
# lives outside the default search list). The identity matters: an ad-hoc signature makes the
# designated requirement a cdhash, so macOS treats every build as a different app and drops its
# Accessibility grant. A certificate makes it `identifier and certificate root`, which is stable.
#
# Re-signing after the fact rather than handing the identity to Xcode is deliberate: Xcode only
# selects identities that pass a trust evaluation, and a self-signed cert never will. It silently
# falls back to ad-hoc instead of failing, which is the worst of both worlds.
set -euo pipefail

SRC="$(cd "$1" && pwd)"
VERSION="$2"
OUT="$(mkdir -p "${3:-$PWD/dist}" && cd "${3:-$PWD/dist}" && pwd)"

# base.xcconfig ends with `#include? "local.xcconfig"`, so these override the upstream release settings.
cat > "$SRC/config/local.xcconfig" <<EOF
// Generated by build.sh — not for redistribution as an official build.

// Upstream's release CI injects the version; without it Info.plist has no CFBundleVersion
// and App.version's force-cast crashes on launch.
CURRENT_PROJECT_VERSION = $VERSION

CODE_SIGN_IDENTITY = -
CODE_SIGN_STYLE = Manual
DEVELOPMENT_TEAM =
OTHER_CODE_SIGN_FLAGS = --deep
ENABLE_HARDENED_RUNTIME = NO

// Xcode 16+ rejects upstream's 10.13 target (supported range starts at 12.0), and raising it
// turns upstream's #available checks into warnings that would otherwise fail the build.
MACOSX_DEPLOYMENT_TARGET = 12.0
SWIFT_TREAT_WARNINGS_AS_ERRORS = NO
EOF

cd "$SRC"
xcodebuild -project alt-tab-macos.xcodeproj -scheme Release -configuration Release -derivedDataPath DerivedData

APP="$SRC/DerivedData/Build/Products/Release/AltTab.app"

if [ -n "${SIGN_IDENTITY:-}" ]; then
  codesign --force --deep --sign "$SIGN_IDENTITY" ${SIGN_KEYCHAIN:+--keychain "$SIGN_KEYCHAIN"} "$APP"
  authority=$(codesign -dv --verbose=2 "$APP" 2>&1 | sed -n 's/^Authority=//p')
  [ -n "$authority" ] || { echo "asked to sign as '$SIGN_IDENTITY' but the app is still ad-hoc" >&2; exit 1; }
  echo "signed by: $authority"
else
  echo "signed by: ad-hoc"
fi

codesign --verify --deep --strict "$APP"
test "$(defaults read "$APP/Contents/Info.plist" CFBundleVersion)" = "$VERSION"
codesign -d -r- "$APP" 2>&1 | sed -n 's/^#* *designated => /designated requirement: /p'

ditto -c -k --keepParent "$APP" "$OUT/AltTab-$VERSION-unlocked.zip"
echo "built $OUT/AltTab-$VERSION-unlocked.zip"
